build.ps1, tests/container.tests.ps1, tests/containerTestCommon.psm1
Add test script to verify that the containers were built correctly.
Usage example (I didn't actually push all the images to my repo):
`./build.ps1 -Test -ImageName travisez13/powershell -Name ubuntu16.04, ubuntu14.04, centos7, fedora27, fedora28 -Channel preview -Pull`
=> Add test script

createAllManifests.ps1, release/preview/centos7/tags.json, release/preview/fedora27/tags.json, release/preview/fedora28/tags.json, release/preview/nanoserver/tags.json, release/preview/ubuntu14.04/tags.json, release/preview/ubuntu16.04/tags.json, release/preview/windowsservercore/tags.json
Adding simpler tags to allow for the creation of the preview manifest list tag.
=> add `preview-*` tags for all preview images

.github/CODEOWNERS, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/stale.yml, assets/README.powershell.md
- Update Readme
- Also added the following to make thing go smoother in the future:
- Add Stale Bot Yml
- Add PR Template
- Add Issue Template
- Add code owners to automatically add reviewers
=> Update readme and add GitHub template

release/preview/ubuntu14.04/docker/Dockerfile, release/preview/ubuntu16.04/docker/Dockerfile, release/preview/ubuntu18.04/docker/Dockerfile, release/stable/ubuntu14.04/docker/Dockerfile, release/stable/ubuntu16.04/docker/Dockerfile
Updating registration of MSFT repo using .deb package.
This follows example set in the [PS installation docs](https://github.com/PowerShell/PowerShell-Docs/pull/2676/files?short_path=9e40516#diff-9e405166c86b24f7f5b2a07a3b7cabfc).
Verified using `./build.ps1 -Build -Name 'ubuntu14.04','ubuntu16.04','ubuntu18.04'`
Fix #24 
- **OR**
=> Updating registration of MSFT repo using deb pkg on Ubuntu

assets/README.powershell.md
=> fix link to fedora 28 docker file

assets/README.powershell.md, createAllManifests.ps1, republish.ps1
update preview to use bionic as the latest Ubuntu image instead of xenial
- **OR**
=> update preview to use bionic as the latest Ubuntu image instead of xenial

assets/README.powershell.md
=> remove note about nanoserver being broken

assets/README.powershell.md
Update readme for `6.1.0` release
- **OR**
=> Update readme for `6.1.0` release

release/stable/ubuntu16.04/docker/Dockerfile
pwsh-preview --> pwsh
- **OR**
=> Fix CMD line

release/stable/ubuntu18.04/docker/Dockerfile
pwsh-preview --> pwsh
- **OR**
=> Fix CMD line to use pwsh instead of pwsh-preview

release/stable/nanoserver/docker/Dockerfile
=> Fix PS_version and some typos

build.ps1, tests/container.tests.ps1, tests/containerTestCommon.psm1
Remove duplicate build steps
- **OR**
=> Remove duplicate build steps

release/preview/ubuntu14.04/docker/Dockerfile, release/preview/ubuntu16.04/docker/Dockerfile, release/preview/ubuntu18.04/docker/Dockerfile, release/servicing/ubuntu14.04/docker/Dockerfile, release/servicing/ubuntu16.04/docker/Dockerfile, release/stable/ubuntu14.04/docker/Dockerfile, release/stable/ubuntu16.04/docker/Dockerfile, release/stable/ubuntu18.04/docker/Dockerfile
Following best practice here. This also puts 1 less package into the images.
- **OR**
=> Changed curl to ADD command

build.ps1, tests/container.tests.ps1, tests/containerTestCommon.psm1
Update build to use ACR build when $env:ACR_NAME is defined
- This is for use when building for release.  That build will login to `az` and user `az acr build` to build
- **OR**
=> Update build to use ACR build when $env:ACR_NAME is defined

build.ps1, release/preview/alpine/docker/Dockerfile, release/stable/alpine/docker/Dockerfile, release/stable/centos7/docker/Dockerfile, release/stable/debian8/docker/Dockerfile, release/stable/debian9/docker/Dockerfile, release/stable/fedora27/docker/Dockerfile, release/stable/fedora28/docker/Dockerfile, release/stable/opensuse423/docker/Dockerfile, tests/container.tests.ps1, tests/containerTestCommon.psm1
Make images use package files from Github
- Add code to set argument needed for labels
- Add tests to verify labels which use arguments
- **OR**
=> Make images use package files from Github

.github/ISSUE_TEMPLATE.md
Clarify where where want PSVersionTable from
- **OR**
=> Clarify where where want PSVersionTable from

tests/container.tests.ps1
fix test case collection for push tests
- **OR**
=> fix push tests

build.ps1, release/preview/alpine/meta.json, release/preview/centos7/meta.json, release/preview/fedora27/meta.json, release/preview/fedora28/meta.json, release/preview/nanoserver/meta.json, release/preview/ubuntu14.04/meta.json, release/preview/ubuntu16.04/meta.json, release/preview/ubuntu18.04/meta.json, release/preview/windowsservercore/meta.json, release/servicing/centos7/meta.json, release/servicing/fedora27/meta.json, release/servicing/nanoserver/meta.json, release/servicing/ubuntu14.04/meta.json, release/servicing/ubuntu16.04/meta.json, release/servicing/windowsservercore/meta.json, release/stable/alpine/meta.json, release/stable/centos7/meta.json, release/stable/debian8/meta.json, release/stable/debian9/meta.json, release/stable/fedora27/meta.json, release/stable/fedora28/meta.json, release/stable/nanoserver/meta.json, release/stable/opensuse423/meta.json, release/stable/ubuntu14.04/meta.json, release/stable/ubuntu16.04/meta.json, release/stable/ubuntu18.04/meta.json, release/stable/windowsservercore/meta.json, tests/containerTestCommon.psm1, tools/buildHelper/buildHelper.psm1
Add ability to build from Azure Blob storage
- Add package format to meta json files in order to calculate the url to the actual file.
- This is only really for building during release builds.  It does nothing during CI.
- Add ability to build a version which has not been released yet.
- **OR**
=> Add ability to build from Azure Blob storage

.vsts-ci/releasePhase.yml, .vsts-ci/releasebuild.yml, build.ps1, tests/container.tests.ps1, tests/containerTestCommon.psm1
Add release build definition
Also:
- special case alpine 6.1 rc.1 version test
- make sure the image name in the image labels always says mcr.microsoft.com
- **OR**
=> Add release build definition

release/community-stable/kali-rolling/docker/Dockerfile
- Update `IMAGE_NAME` value for #65 
- Fix Dockerfile build sequence
- Fix `apt-get install -y` package dependencies sequence to alphabetical order align with [Docker's Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#sort-multi-line-arguments)
- Add comments for the community
- **OR**
=> Community - Kali Linux - Dockerfile Minor Fixes

release/preview/alpine/docker/Dockerfile, release/preview/centos7/docker/Dockerfile, release/preview/centos7/meta.json, release/preview/fedora27/docker/Dockerfile, release/preview/fedora27/meta.json, release/preview/fedora28/docker/Dockerfile, release/preview/fedora28/meta.json, release/preview/nanoserver/docker/Dockerfile, release/preview/ubuntu14.04/docker/Dockerfile, release/preview/ubuntu14.04/meta.json, release/preview/ubuntu16.04/docker/Dockerfile, release/preview/ubuntu16.04/meta.json, release/preview/ubuntu18.04/docker/Dockerfile, release/preview/ubuntu18.04/meta.json
Make preview Docker files use packages from storage or GitHub
- Fix incidental typos found while updating files
- **OR**
=> Make preview Docker files use packages from storage or GitHub

.vsts-ci/phase.yml, build.ps1, release/community-stable/kali-rolling/meta.json, release/stable/windowsservercore/docker/Dockerfile, tests/container.tests.ps1, tests/containerTestCommon.psm1, tools/buildHelper/buildHelper.psm1, vsts-ci.yml
Add community channel build and CI
- Also add the ability to disable web CmdLet tests, as they are broken in Kali
- **OR**
=> Add community channel build and CI

.vsts-ci/releasePhase.yml, .vsts-ci/releasebuild.yml, build.ps1, release/preview/nanoserver/docker/Dockerfile, release/preview/windowsservercore/docker/Dockerfile, release/servicing/nanoserver/docker/Dockerfile, release/servicing/windowsservercore/docker/Dockerfile, release/stable/nanoserver/docker/Dockerfile, release/stable/windowsservercore/docker/Dockerfile, tests/containerTestCommon.psm1
Add code to build from storage account during release build
- Automatically generate sastoken url needed by build script
- Fix sasurl validation
- Always run manifest phases now that we are running on staging.
- Escape `&` as `%26` when running in ACR due to different escaping needs for CMD (local) and BASH (ACR)
- **OR**
=> Add code to build from storage account during release build

.vsts-ci/communityReleaseBuild.yml
Add community release build YAML
- This is used to build to https://hub.docker.com/r/pshorg/powershellcommunity/tags/
- This is not built by Microsoft
- **OR**
=> Add community release build YAML

release/preview/alpine/docker/Dockerfile, release/preview/alpine/meta.json
Enable building alpine images.
- **OR**
=> Enable building alpine images from tar.gz

release/community-stable/photon/docker/Dockerfile
- Add VMware's Photon Linux image to release/community-stable for #95 
- Include PowerShell Module Analysis Cache Path
fixes #95
The path is setup on `/var/cache/microsoft/powershell/PSModuleAnalysisCache/ModuleAnalysisCache` to respect Linux File System structure.
- **OR**
=> Add PowerShell Core in VMware Photon Linux image Dockerfile

release/preview/alpine/docker/Dockerfile, release/preview/centos7/docker/Dockerfile, release/preview/debian8/docker/Dockerfile, release/preview/debian8/getLatestTag.ps1, release/preview/debian8/meta.json, release/preview/debian8/tags.json, release/preview/debian9/docker/Dockerfile, release/preview/debian9/getLatestTag.ps1, release/preview/debian9/meta.json, release/preview/debian9/tags.json, release/preview/fedora27/docker/Dockerfile, release/preview/fedora28/docker/Dockerfile, release/preview/opensuse423/docker/Dockerfile, release/preview/opensuse423/getLatestTag.ps1, release/preview/opensuse423/meta.json, release/preview/opensuse423/tags.json, release/preview/ubuntu14.04/docker/Dockerfile, release/preview/ubuntu16.04/docker/Dockerfile, release/preview/ubuntu18.04/docker/Dockerfile, release/stable/alpine/docker/Dockerfile, release/stable/centos7/docker/Dockerfile, release/stable/debian8/docker/Dockerfile, release/stable/debian9/docker/Dockerfile, release/stable/fedora27/docker/Dockerfile, release/stable/fedora28/docker/Dockerfile, release/stable/opensuse423/docker/Dockerfile, release/stable/ubuntu14.04/docker/Dockerfile, release/stable/ubuntu16.04/docker/Dockerfile, release/stable/ubuntu18.04/docker/Dockerfile, tests/containerTestCommon.psm1
Port debian and opensuse to preview channel
- **OR**
=> Port debian and opensuse to preview channel

.github/PULL_REQUEST_TEMPLATE.md, .markdownlint.json, assets/README.powershell.md, assets/about_readme.powershell.md
Update supported image readme to MCR 2.0 format
- Add file describing what changes are allowed in the readme
- remove the requirement to update readme for new tag as the tag listing is generated.
- **OR**
=> Update supported image readme to MCR 2.0 format

release/preview/alpine/meta.json, release/preview/alpine/tags.json, release/stable/alpine/docker/Dockerfile, release/stable/alpine/meta.json, release/stable/alpine/tags.json
Update stable Alpine image to use new complete package
- Also move Alpine tag templates into meta.json
- **OR**
=> Update stable Alpine image to use new complete package

release/stable/arm32v7/docker/Dockerfile
=> Incrementing PowerShell version to 6.1.2

release/community-stable/archlinux/docker/Dockerfile, release/community-stable/archlinux/getLatestTag.ps1, release/community-stable/blackarch/docker/Dockerfile, release/community-stable/blackarch/getLatestTag.ps1, vsts-ci.yml
Repo info for archlinux change, so I'm updating the build
- **OR**
=> Update repo info for arch

release/preview/centos7/docker/Dockerfile, release/servicing/centos7/docker/Dockerfile, release/stable/centos7/docker/Dockerfile
from #124 
edit: failures seem unrelated to this change
please don't make me fill this out 🐙 
cc @TravisEz13
=> Add libraries needed for NTLM to centos images

build.ps1, release/community-stable/amazonlinux/meta.json, release/community-stable/kali-rolling/meta.json, release/community-stable/oraclelinux/meta.json, release/community-stable/parrot/getLatestTag.ps1, release/community-stable/parrot/meta.json, release/community-stable/photon/meta.json, release/preview/alpine/meta.json, release/preview/debian9/meta.json, release/preview/fedora28/meta.json, release/preview/opensuse423/meta.json, release/preview/ubuntu14.04/meta.json, release/preview/ubuntu16.04/meta.json, release/preview/ubuntu18.04/meta.json, release/servicing/ubuntu14.04/meta.json, release/servicing/ubuntu16.04/meta.json, release/stable/alpine/meta.json, release/stable/debian9/meta.json, release/stable/fedora28/meta.json, release/stable/opensuse423/meta.json, release/stable/ubuntu14.04/meta.json, release/stable/ubuntu16.04/meta.json, release/stable/ubuntu18.04/meta.json, release/stable/ubuntu18.04/tags.json, tests/container.tests.ps1, tests/containerTestCommon.psm1, tools/buildHelper/buildHelper.psm1, vsts-ci.yml
Add test for Linux NTLM library
- **OR**
=> Add test for Linux NTLM library

release/preview/ubuntu14.04/meta.json, release/preview/ubuntu14.04/tags.json, release/preview/ubuntu16.04/meta.json, release/preview/ubuntu16.04/tags.json, release/preview/ubuntu18.04/meta.json, release/preview/ubuntu18.04/tags.json, release/stable/ubuntu14.04/meta.json, release/stable/ubuntu14.04/tags.json, release/stable/ubuntu16.04/meta.json, release/stable/ubuntu16.04/tags.json
Moves some of the meta stuff
- **OR**
=> Move tag templates

release/servicing/ubuntu14.04/meta.json, release/servicing/ubuntu14.04/tags.json, release/servicing/ubuntu16.04/meta.json, release/servicing/ubuntu16.04/tags.json
=> Finish moving ubuntu tag stuff

.vsts-ci/releasebuild.yml
Save the release tag variable from the release build so we can automate the actual release
- **OR**
=> Save variables

build.ps1, release/preview/nanoserver/docker/Dockerfile, release/preview/nanoserver/meta.json, release/preview/nanoserver1809/docker/Dockerfile, release/preview/nanoserver1809/meta.json, release/preview/windowsservercore/docker/Dockerfile, release/preview/windowsservercore/meta.json, release/stable/nanoserver/docker/Dockerfile, release/stable/nanoserver/meta.json, release/stable/nanoserver1809/docker/Dockerfile, release/stable/nanoserver1809/meta.json, release/stable/windowsservercore/docker/Dockerfile, release/stable/windowsservercore/meta.json, tests/containerTestCommon.psm1, tools/buildHelper/buildHelper.psm1
Add support for the build system passing urls into the dockerfile base64 encoded
- **OR**
=> Add support for the build system passing urls into the dockerfile base64 encoded

release/community-stable/photon/meta.json, release/community-stable/photon/tags.json
=> Move photon tag templates

build.ps1, release/preview/windowsservercore/meta.json, release/servicing/windowsservercore/meta.json, release/stable/windowsservercore/meta.json, tests/container.tests.ps1
Fix WindowsServerCore package template
- Also, fix the pull tests for windows
- **OR**
=> Fix WindowsServerCore package template

release/community-stable/parrot/meta.json, release/community-stable/parrot/tags.json
title explains it all
- **OR**
=> Move parrot tag templates

build.ps1
Add tag filter used to allow testing in process isolation
With Process isolation the version of windows must match
- **OR**
=> Add tag filter used to allow testing in process isolation

release/community-stable/clearlinux/meta.json, release/community-stable/clearlinux/tags.json
Moves clearlinux tag templates
- **OR**
=> Move clearlinux tag templates

release/community-stable/blackarch/meta.json, release/community-stable/blackarch/tags.json
=> Move blackarch tag templates

release/community-stable/oraclelinux/meta.json, release/community-stable/oraclelinux/tags.json
=> Move oraclelinux tag templates

vsts-ci.yml
=> Fix azure devops

release/community-stable/amazonlinux/meta.json, release/community-stable/amazonlinux/tags.json
title explains it all
- **OR**
=> Move amazonlinux tag templates

release/community-stable/archlinux/docker/Dockerfile, release/community-stable/blackarch/docker/Dockerfile
=> Fix grammar issue in Docker file comment

release/community-stable/kali-rolling/meta.json, release/community-stable/kali-rolling/tags.json, release/preview/windowsservercore/meta.json, release/preview/windowsservercore/tags.json, release/servicing/windowsservercore/meta.json, release/servicing/windowsservercore/tags.json, release/stable/windowsservercore/meta.json, release/stable/windowsservercore/tags.json
=> Moved more tagtemplates

.github/ISSUE_TEMPLATE.md, build.ps1, tests/containerTestCommon.psm1
=> Documentation cleanup + make the first letter of Docker uppercase

LICENSE.txt
On the line above it it says the same thing 
- **OR**
=> Remove redundant sentence from license

release/stable/opensuse423/meta.json, release/stable/opensuse423/tags.json
=> Move opensuse423 tag templates

release/preview/centos7/meta.json, release/preview/centos7/tags.json, release/servicing/centos7/meta.json, release/servicing/centos7/tags.json, release/stable/centos7/meta.json, release/stable/centos7/tags.json
=> Move CentOS tag templates

release/preview/fedora28/meta.json, release/preview/fedora28/tags.json, release/stable/fedora28/meta.json, release/stable/fedora28/tags.json
=> Move fedora28 tag templates

.vsts-ci/releasebuild.yml, build.ps1, release/preview/ubuntu14.04/meta.json, release/preview/ubuntu16.04/meta.json, release/preview/ubuntu18.04/meta.json, vsts-ci.yml
Resolve duplicate tags, by giving short tags in ubuntu images the `preview-` syntax again.
- Also, add tests to keep this from happening again.
- **OR**
=> Resolve duplicate tags

build.ps1, tools/buildHelper/buildHelper.psm1
Refactor some of the build code into buildHelper to make the build more maintainable.
- **OR**
=> Refactor some of the build code into buildHelper

build.ps1
Make CI use package template.
Fixes #140
- **OR**
=> Make CI use package template

release/preview/nanoserver/docker/Dockerfile, release/preview/nanoserver1809/docker/Dockerfile, release/preview/windowsservercore/docker/Dockerfile, release/stable/nanoserver/docker/Dockerfile, release/stable/nanoserver1809/docker/Dockerfile, release/stable/windowsservercore/docker/Dockerfile
Add module cache analysis to Windows Images
- **OR**
=> Add module cache analysis to Windows Images

tests/container.tests.ps1
Remove special case for Alpine version test
- **OR**
=> Remove special case for Alpine version test

.vsts-ci/releasePhase.yml, release/community-stable/clearlinux/meta.json, vsts-ci.yml
Select subscription and standardize variable names in release build
Also, disable ClearLinux web cmdlet tests due to #172 	
- **OR**
=> Select subscription and standardize variable names in release build

release/community-stable/archlinux/meta.json, release/community-stable/archlinux/tags.json
=> Move ArchLinux tag templates

README.md
This is a grammar fix, it is also to see if CI will fail on this PR (no code changes)
- **OR**
=> The f in Dockerfile is lowercase (grammar fix)

release/preview/debian9/docker/Dockerfile, release/preview/debian9/meta.json, release/stable/debian9/docker/Dockerfile, release/stable/debian9/meta.json
=> Add support for NTLM on Debian

release/preview/fedora28/docker/Dockerfile, release/preview/fedora28/meta.json, release/stable/fedora28/docker/Dockerfile, release/stable/fedora28/meta.json
=> Add support for NTLM on Fedora

.poshchan/settings.json
=> add settings for poshchan

.poshchan/settings.json
* enable `Please rebuild` for `docker-PR`
* whitelist anmenaga because he is a code owner and myself so I can set reminders (I am quite forgetful)
- **OR**
=> Update poshchan config

.poshchan/settings.json
Last PR had an intermediate format change, but forgot I had made another change to have permissions under the action vs it's own section so this new format should be more maintainable and readable and aligns with current PoshChan code.
- **OR**
=> Fix PoshChan settings to latest format

release/preview/opensuse423/meta.json, release/preview/opensuse423/tags.json
=> Move opensuse preview tagtemplates

release/community-stable/oraclelinux/docker/Dockerfile, release/community-stable/oraclelinux/meta.json, vsts-ci.yml
=> Add partial NTLM support to oraclelinux

.vsts-ci/phase.yml, release/community-stable/amazonlinux/docker/Dockerfile, release/community-stable/amazonlinux/meta.json
This should work (I hope)
EDIT: the image builds but the extra gssntlmssp tests fail
- **OR**
=> Add NTLM remoting support to amazonlinux

tests/container.tests.ps1
Fix linux test failure
- **OR**
=> Fix linux test failure

.vsts-ci/misc-analysis.yml, .vsts-ci/templates/credscan.yml
Add a CI YAML that will scan for secrets.
This will prevents secrets from accidentally being added to the repo.
- **OR**
=> Add secret scan CI

.vsts-ci/communityReleaseBuild.yml
=> Add Community Release build

.vsts-ci/phase.yml, build.ps1, release/stable/nanoserver/getLatestTag.ps1, release/stable/nanoserver1809/getLatestTag.ps1, tools/buildHelper/buildHelper.psm1, tools/getDockerTags/getDockerTags.psm1, vsts-ci.yml
refactor to prepare for adding sub-images
related to #200 
- **OR**
=> refactor to prepare for adding sub-images

.poshchan/settings.json
Update PoshChan settings.json
- **OR**
=> Update PoshChan settings.json

build.ps1, release/stable/centos7/test-deps/docker/Dockerfile, tests/containerTestCommon.psm1, tools/buildHelper/buildHelper.psm1, vsts-ci.yml
Fix various release build issues
- `--os` was disable and `--platform` has to be used
- Fix tagsyaml generation after adding subrepos (in #202)
- **OR**
=> Fix various release build issues

tools/buildHelper/buildHelper.psm1
fix issue with tests failing in release process
- **OR**
=> fix issue with tests failing in release process

docs/development.md
* minor fixes
* grammar
* redundant stuff
* add CI template
- **OR**
=> Update development docs

.vsts-ci/communityReleaseBuild.yml, .vsts-ci/releasebuild.yml, tests/containerTestCommon.psm1, vsts-ci.yml
Opt tests out of telemetry
- **OR**
=> Opt tests out of telemetry

release/preview/debian9/meta.json, release/preview/debian9/test-deps/docker/Dockerfile, release/preview/debian9/test-deps/meta.json, release/stable/debian9/meta.json, release/stable/debian9/test-deps/docker/Dockerfile, release/stable/debian9/test-deps/meta.json, tests/container.tests.ps1, tests/containerTestCommon.psm1
Add debian test-dep image
- Also, add more tests to verify test dependencies are there
- Also, add more tests to verify that base image utilities are there
- **OR**
=> Add debian test-dep image

release/preview/ubuntu16.04/meta.json, release/preview/ubuntu16.04/test-deps/docker/Dockerfile, release/preview/ubuntu16.04/test-deps/meta.json, release/preview/ubuntu18.04/meta.json, release/preview/ubuntu18.04/test-deps/docker/Dockerfile, release/preview/ubuntu18.04/test-deps/meta.json, release/stable/debian9/test-deps/docker/Dockerfile, release/stable/ubuntu16.04/meta.json, release/stable/ubuntu16.04/test-deps/docker/Dockerfile, release/stable/ubuntu16.04/test-deps/meta.json, release/stable/ubuntu18.04/meta.json, release/stable/ubuntu18.04/test-deps/docker/Dockerfile, release/stable/ubuntu18.04/test-deps/meta.json
Add Ubuntu test-deps images
- **OR**
=> Add Ubuntu test-deps images

release/community-stable/archlinux/docker/Dockerfile, release/community-stable/blackarch/docker/Dockerfile, release/community-stable/parrot/docker/Dockerfile, release/community-stable/photon/docker/Dockerfile, release/preview/alpine/docker/Dockerfile, release/preview/opensuse423/docker/Dockerfile, release/servicing/alpine/docker/Dockerfile, release/stable/alpine/docker/Dockerfile, tests/container.tests.ps1, tests/containerTestCommon.psm1, tools/buildHelper/buildHelper.psm1, vsts-ci.yml
Fix alpine test dep images
- Also, add tests cases as this is the second image with this issue
- **OR**
=> Fix alpine test dep images

release/preview/centos7/meta.json, release/preview/centos7/test-deps/meta.json, release/preview/debian9/docker/Dockerfile, release/preview/debian9/getLatestTag.ps1, release/stable/centos7/meta.json, release/stable/centos7/test-deps/meta.json, release/stable/debian9/docker/Dockerfile, release/stable/debian9/getLatestTag.ps1
=> Use slim images for Deb9

release/preview/alpine/docker/Dockerfile, release/preview/centos7/docker/Dockerfile, release/preview/debian9/docker/Dockerfile, release/preview/fedora28/docker/Dockerfile, release/preview/opensuse423/docker/Dockerfile, release/preview/ubuntu16.04/docker/Dockerfile, release/preview/ubuntu18.04/docker/Dockerfile, tests/container.tests.ps1
Update the PSHome path for use the `7` version number.
- **OR**
=> Update PSHOME path for 7-preview

release/preview/opensuse423/docker/Dockerfile, release/preview/opensuse423/getLatestTag.ps1, release/stable/opensuse423/docker/Dockerfile, release/stable/opensuse423/getLatestTag.ps1
=> Update opensuse images to leap from 42.3

build.ps1, release/preview/debian9/getLatestTag.ps1, release/stable/debian9/getLatestTag.ps1, tools/buildHelper/buildHelper.psm1, tools/getDockerTags/getDockerTags.psm1
=> Fix Debian build

.dependabot/config.yml, vsts-ci.yml
=> Update dependabot config

release/community-stable/amazonlinux/docker/Dockerfile, release/community-stable/amazonlinux/test-deps/docker/Dockerfile, release/community-stable/archlinux/docker/Dockerfile, release/community-stable/blackarch/docker/Dockerfile, release/community-stable/clearlinux/docker/Dockerfile, release/community-stable/kali-rolling/docker/Dockerfile, release/community-stable/oraclelinux/docker/Dockerfile, release/community-stable/parrot/docker/Dockerfile, release/community-stable/photon/docker/Dockerfile
Add this for completeness. This will be used only when PowerShell 7 becomes stable.
- **OR**
=> Add dist channel to community

release/preview/nanoserver1809/docker/Dockerfile, release/stable/nanoserver1809/docker/Dockerfile
Set the path as ContainerAdministration as a machine variable
Fixes #272
- **OR**
=> Set the path as ContainerAdministration as a machine variable

.dependabot/config.yml, release/preview/centos8/dependabot/Dockerfile, release/preview/centos8/docker/Dockerfile, release/preview/centos8/getLatestTag.ps1, release/preview/centos8/meta.json, release/preview/centos8/test-deps/docker/Dockerfile, release/preview/centos8/test-deps/meta.json, vsts-ci.yml
=> Add centos8 image

docs/index.md
=> Document image purpose

release/community-stable/clearlinux/docker/Dockerfile, release/community-stable/clearlinux/meta.json
Mirror #177 
Since it can't be opened, I've recreated it
- **OR**
=> ClearLinux: Set SkipWebCmdletTests to false - Mirror #177

build.ps1
=> Minor tweaks and improvements to build.ps1

release/stable/arm32v7/docker/Dockerfile
Update Dockerfile for ARM to PowerShell Core 6.2.3. Test on Raspberry Pi 3 B+ with Raspbian 9.11 Stretch
- **OR**
=> Update Dockerfile for ARM to PowerShell Core 6.2.3

.vsts-ci/phase.yml, release/community-stable/kali-rolling/getLatestTag.ps1, release/community-stable/parrot/docker/Dockerfile, release/community-stable/parrot/getLatestTag.ps1, vsts-ci.yml
Fix kali tag selection
- **OR**
=> Fix kali tag selection

.gitpod.Dockerfile
Fix GitPod
cc @RDIL , FYI I messaged you on twitter.
Did you get the PowerShell or Docker extension working?
- **OR**
=> Fix GitPod

.vsts-ci/phase.yml, .vsts-ci/releasePhase.yml, tools/getDockerTags/getDockerTags.psm1
Add retry for retrieving tag list
- **OR**
=> Add retry for retrieving tag list

assets/README.powershell.md
=> Sync readme with MCR

.vsts-ci/phase.yml, build.ps1, vsts-ci.yml
=> Install pester if it isn't already installed

tools/buildHelper/buildHelper.psm1
=> Disabled clearlinux so community build passes for now

tests/container.tests.ps1
=> Skip pushing when using ACR

release/community-stable/clearlinux/meta.json, release/community-stable/kali-rolling/meta.json, release/community-stable/parrot/meta.json, tools/buildHelper/buildHelper.psm1
@TravisEz13 please merge this without the 24 hour period, I really want to see if this fixes it.
=> Add metadata to skip failing images

release/community-stable/photon/docker/Dockerfile, release/preview/fedora/meta.json, release/preview/fedora/test-deps/meta.json
=> Update PS version for photon

release/preview/fedora/docker/Dockerfile
Fix Fedora 28 failure
- **OR**
=> Fix Fedora 28 failure

MAINTAINERS, release/community-stable/archlinux/docker/Dockerfile, release/community-stable/blackarch/docker/Dockerfile, release/community-stable/kali-rolling/docker/Dockerfile, release/community-stable/oraclelinux/docker/Dockerfile, release/community-stable/oraclelinux/meta.json, release/community-stable/parrot/docker/Dockerfile, release/preview/centos7/test-deps/docker/Dockerfile, release/preview/centos8/test-deps/docker/Dockerfile, release/preview/debian9/docker/Dockerfile, release/preview/ubuntu16.04/docker/Dockerfile, release/preview/ubuntu18.04/docker/Dockerfile, release/servicing/arm32v7/docker/Dockerfile, release/servicing/debian9/docker/Dockerfile, release/servicing/ubuntu16.04/docker/Dockerfile, release/servicing/ubuntu18.04/docker/Dockerfile, release/stable/arm32v7/docker/Dockerfile, release/stable/centos7/test-deps/docker/Dockerfile, release/stable/debian9/docker/Dockerfile, release/stable/ubuntu16.04/docker/Dockerfile, release/stable/ubuntu18.04/docker/Dockerfile
Many of the final containers end up 40MB-50MB larger than they need to be due to how some of the `.tar.gz` and `.deb` files are downloaded. In some instances, the `yum` cache could be cleared out as well.
This PR makes the changes necessary for several of the final images to end up smaller. Most of the changes fell into one category:
- Making it so that already-existing `rm` commands _actually_ remove the files no longer needed
In many instances, files were simply brought in via an `ADD` command and were later `rm`'d. This doesn't _actually_ result in the final image being smaller. In order for a file removal to actually result in a smaller image size, the file in question must be removed in the same layer in which it was introduced.
Example: After the changes to `stable/debian9`, the …
=> Slim down some of the final images

docs/terms.md
=> Add terms page

.vsts-ci/phase.yml, .vsts-ci/vsts-arm-ci.yml, release/preview/nanoserver1809/meta.json, release/preview/windowsservercore/getLatestTag.ps1, release/stable/nanoserver1809/meta.json, release/stable/windowsservercore/getLatestTag.ps1
=> Add 1909 images

.vsts-ci/releasePhase.yml, .vsts-ci/releasebuild.yml, build.ps1, tools/buildHelper/buildHelper.psm1, vsts-ci.yml
=> Add lts to release build

release/lts/alpine38/docker/Dockerfile, release/lts/alpine39/docker/Dockerfile, release/lts/arm32v7/docker/Dockerfile, release/lts/centos7/docker/Dockerfile, release/lts/centos7/meta.json, release/lts/centos8/docker/Dockerfile, release/lts/centos8/meta.json, release/lts/debian10/docker/Dockerfile, release/lts/debian10/test-deps/docker/Dockerfile, release/lts/debian11/docker/Dockerfile, release/lts/debian11/test-deps/docker/Dockerfile, release/lts/debian9/docker/Dockerfile, release/lts/debian9/meta.json, release/lts/fedora/docker/Dockerfile, release/lts/fedora/meta.json, release/lts/ubuntu16.04/docker/Dockerfile, release/lts/ubuntu16.04/meta.json, release/lts/ubuntu18.04/docker/Dockerfile, release/lts/ubuntu18.04/meta.json, release/lts/windowsservercore/docker/Dockerfile, tests/container.tests.ps1
=> Make tests that rely on executable path use common code to calculate path

.dependabot/config.yml, release/preview/alpine311/dependabot/Dockerfile, release/preview/alpine311/docker/Dockerfile, release/preview/alpine311/getLatestTag.ps1, release/preview/alpine311/meta.json, release/preview/alpine311/test-deps/docker/Dockerfile, release/preview/alpine311/test-deps/meta.json, release/preview/alpine38/test-deps/docker/Dockerfile, release/preview/alpine39/test-deps/docker/Dockerfile, vsts-ci.yml
=> Alpine 3.11

.vsts-ci/releasebuild.yml
=> use standard build pool

release/preview/alpine311/test-deps/meta.json, release/preview/alpine38/test-deps/meta.json, release/preview/alpine39/test-deps/meta.json
Increase size allowed for alpine test-deps
- **OR**
=> Increase size allowed for alpine test-deps

.vsts-ci/communityReleasePhase.yml
=> fix community image name

release/lts/alpine38/meta.json, release/lts/alpine39/meta.json, release/preview/alpine311/meta.json, release/preview/alpine38/meta.json, release/preview/alpine39/meta.json, release/stable/alpine38/meta.json, release/stable/alpine39/meta.json
=> Update alpine image size

.vsts-ci/releasebuild.yml, release/preview/alpine311/meta.json, release/preview/alpine311/test-deps/meta.json, release/preview/alpine38/meta.json, release/preview/alpine38/test-deps/meta.json, release/preview/alpine39/meta.json, release/preview/alpine39/test-deps/meta.json, release/preview/centos8/meta.json, release/preview/centos8/test-deps/meta.json, tests/container.tests.ps1
increase image sizes for 7.1 preview 4 release
- **OR**
=> increase image sizes for 7.1 preview 4 release

.github/ISSUE_TEMPLATE.md, README.md
Make known issues clearer in readme and issues template
- Known issues have been moved to wiki for easier editting
Fixes #418 
- **OR**
=> Make known issues clearer in readme and issues template

.vsts-ci/communityReleasePhase.yml, .vsts-ci/phase.yml, .vsts-ci/releasePhase.yml, .vsts-ci/releasebuild.yml, build.ps1, tools/.gitpod.Dockerfile
Pin to version 4 of Pester
Version 5 is forcing tests to run in strict mode.
- **OR**
=> change to trigger a PR

release/community-stable/parrotsec/docker/Dockerfile
- Align with ParrotSec recommendations;
- Replace `apt-get` with `apt`
- Replace `apt-get dist-upgrade` with `parrot-upgrade`
- Fix other miscellaneous minor item
- **OR**
=> Update ParrotSec commands

release/lts/centos8/meta.json, release/lts/centos8/test-deps/meta.json, release/preview/centos8/meta.json, release/preview/centos8/test-deps/meta.json, release/stable/centos8/meta.json, release/stable/centos8/test-deps/meta.json
=> Fix CentOS image size

createAllManifests.ps1, createManifest.ps1, release/lts/debian11/docker/Dockerfile, release/preview/debian11/docker/Dockerfile, release/stable/debian11/docker/Dockerfile
=> Fix manifest creation

LICENSE.txt
* Update LICENSE so that Github recognizes it as MIT.
* Remove the term All Rights Reserved as Microsoft no longer recommend it.
See also: https://github.com/PowerShell/PowerShell/pull/12729
=> Update `LICENSE.txt` so that it's recognized as MIT

.editorconfig
* Specify charset as UTF-8 (without BOM)
* Verified no files contain UTF-8 BOM
- **OR**
- [NA] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/docs/README.powershellcommunity.md)
- [NA] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)
=> Add .editorconfig file to specify charset 

.vsts-ci/releasePhase.yml, .vsts-ci/templatesGeneric/setVersionStepsTemplate.yml
Refactor set version to template
- **OR**
=> Refactor set version to template

.vsts-ci/releasePipeline.yml, .vsts-ci/templatesGeneric/deserializeTags.ps1, .vsts-ci/templatesReleasePipeline/releaseJob.yml, .vsts-ci/templatesReleasePipeline/releaseStage.yml, .vsts-ci/templatesReleasePipeline/testAndRelease.yml, .vsts-ci/templatesReleasePipeline/testJob.yml, .vsts-ci/templatesReleasePipeline/testStage.yml, build.ps1, tools/buildHelper/buildHelper.psm1
Refactor release into yaml with a matrix 
- **OR**
=> Refactor release into yaml with a matrix

release/preview/alpine310/meta.json
=> Fix Alpine 3.10 preview size

.vsts-ci/templatesReleasePipeline/releaseJob.yml, .vsts-ci/templatesReleasePipeline/testStage.yml
* disable size tests during release
* set version in json used to replicate images
- **OR**
=> Fix release

.vsts-ci/releasePipeline.yml, .vsts-ci/templatesReleasePipeline/releaseStage.yml, build.ps1, tests/container.tests.ps1, tests/containerTestCommon.psm1
=> Fix release test failures

release/preview/ubuntu20.04/docker/Dockerfile
=> create `pwsh-preview` symlink

.vsts-ci/releasePipeline.yml
changing the environment for the release pipeline create MCR docs stage
- **OR**
=> change the environment for the release pipeline create MCR docs stage

.github/dependabot.yml, release/community-stable/oraclelinux/dependabot/Dockerfile, release/community-stable/oraclelinux/meta.json
Not sure if I'm getting this correct.
- Added dependabot Dockerfile into community-stable OracleLinux folder
- Updated Dependabot yaml file with the configuration
- Updated the meta file of OracleLinux
- **OR**
=> Community-Stable OracleLinux: Add Dependabot capability

.vsts-ci/manifestSteps.yml, .vsts-ci/releasebuild.yml, build.ps1, createAllManifests.ps1, release/lts/nanoserver1809/meta.json, release/lts/nanoserver1909/meta.json, release/lts/nanoserver2004/meta.json, release/lts/ubuntu18.04/meta.json, release/lts/windowsservercore1909/meta.json, release/lts/windowsservercore2004/meta.json
Generate manifest lists for LTS channel. Update meta.json for the LTS channel images as well.
WIP because I'm not yet fully sure if I used the right values for the manifestList key/value in the meta.json files.
Addresses #527 
- **OR**
=> Add LTS tag and push manifest lists for LTS

release/preview/centos7/meta.json, release/preview/centos8/meta.json, release/preview/debian9/meta.json, release/preview/fedora32/meta.json, release/preview/ubuntu16.04/meta.json, release/preview/ubuntu18.04/meta.json
Update to use universal package names
- **OR**
=> Update to use universal package names

release/preview/fedora32/meta.json
=> make short tag work for fedora 32

.vsts-ci/releasePhase.yml, .vsts-ci/releaseStage.yml, .vsts-ci/templatesReleasePipeline/releaseJob.yml, .vsts-ci/templatesReleasePipeline/releaseManifestList.yml, build.ps1
Update manifest list and tag yaml for changes that allow internal images
- correct format for source image when importing manifest list into ACR
- don't put internal images in tags yaml
Also
- Update parameter format into the new format
- **OR**
=> Update manifest list and tag YAML for changes that allow internal images

release/preview/nanoserver2022/docker/Dockerfile, release/preview/nanoserver2022/meta.json, release/preview/windowsservercore2022/docker/Dockerfile, release/preview/windowsservercore2022/meta.json
Create Preview images for nanoserver 2022 and windowsservercore 2022
- **OR**
=> Preview 2022 images

.vsts-ci/releasePhase.yml, build.ps1
=> Add matrix parameter

release/preview/nanoserver2022/meta.json, release/preview/windowsservercore2022/meta.json
Remove manifest list from 2022 preview images
- **OR**
=> remove manifest list from 2022 preview images

release/preview/alpine311/test-deps/docker/Dockerfile, release/preview/alpine312/test-deps/docker/Dockerfile, release/preview/alpine313/test-deps/docker/Dockerfile, release/stable/alpine311/test-deps/docker/Dockerfile, release/stable/alpine312/test-deps/docker/Dockerfile, release/stable/alpine313/test-deps/docker/Dockerfile
It's been a while, Node has had many patches (including security ones) since these, so it's now on the latest LTS.
- **OR**
=> Update node version in test-deps

release/preview/nanoserver2022/meta.json, release/preview/windowsservercore2022/meta.json
Add manifest list in meta.json file for nanoserver2022 and windowsservercore2022 images as they are now public.
- **OR**
=> add manifest list to 2022 preview images

.github/ISSUE_TEMPLATE.md
Uservoice is no longer used by Microsoft. The old uservoice link results in 404.
- **OR**
=> Change link to Windows Feedback Hub

.github/workflows/update.yml, tools/updateScript.ps1
=> Add workflow to update the release build parameters

.github/workflows/update.yml
=> Fix release build parameter PR description

.vsts-ci/releasebuild.yml
Updated `releasebuild.yml` to use `ubuntu-latest` image
- **OR**
=> Updated `releasebuild.yml` to use `ubuntu-latest` image

release/lts/centos7/meta.json, release/lts/centos7/test-deps/meta.json, release/preview/alpine311/test-deps/meta.json, release/preview/alpine312/test-deps/meta.json, release/preview/alpine313/test-deps/meta.json, release/preview/alpine314/test-deps/meta.json, release/stable/centos7/meta.json, release/stable/centos7/test-deps/meta.json, tools/buildHelper/buildHelper.psm1, vsts-ci.yml
* Quit using regex tag mappings for alpine test-dep
* Update centos7 image sizes
* Update to new image from credscan
* Only use first LTS ReleaseTag
- **OR**
=> Fix alpine missing test-deps

release/preview/fedora34/docker/Dockerfile, release/preview/fedora34/meta.json, release/preview/fedora34/test-deps/docker/Dockerfile, release/preview/fedora34/test-deps/meta.json, release/stable/fedora34/docker/Dockerfile, release/stable/fedora34/meta.json, release/stable/fedora34/test-deps/docker/Dockerfile, release/stable/fedora34/test-deps/meta.json
Update Fedora 32 to Fedora 34 for preview 
- **OR**
=> Update Fedora 32 to Fedora 34 for preview

docs/README.powershell.md
bring change by MCR back here
- **OR**
=> sync readme from MCR

release/stable/ubuntu20.04/docker/Dockerfile
Typo in comments of Dockerfile. Misspelling on comments.
- **OR**
=> minor edit - typo in comments

.github/PULL_REQUEST_TEMPLATE.md, release/preview/mariner1/docker/Dockerfile, release/preview/mariner1/meta.json, release/preview/mariner1/test-deps/docker/Dockerfile, release/preview/mariner1/test-deps/meta.json, tools/buildHelper/buildHelper.psm1
Add mariner 1.0 image
- **OR**
=> Add mariner 1.0 image

.vsts-ci/releasePhase.yml, .vsts-ci/releaseStage.yml, .vsts-ci/releasebuild.yml, .vsts-ci/templatesReleasePipeline/releaseJob.yml, .vsts-ci/templatesReleasePipeline/releaseManifestList.yml, .vsts-ci/templatesReleasePipeline/releaseStage.yml, .vsts-ci/templatesReleasePipeline/testJob.yml, .vsts-ci/templatesReleasePipeline/testStage.yml
Switch to using standard images for release build
=> Switch to using standard images for release build

release/preview/mariner1/meta.json
=> Fix mariner tag generation

build.ps1, release/community-stable/amazonlinux/meta.json, release/community-stable/amazonlinux/test-deps/meta.json, release/preview/mariner1/docker/Dockerfile, release/preview/mariner1/meta.json
* Add osVersion for mariner
* Fail if an image doesn't have osVersion
* Switch to tdnf per mariner
=> Add osVersion to mariner

release/preview/mariner1/docker/Dockerfile
=> Pull mariner from MCR

release/7-2/ubuntu22.04/docker/Dockerfile, release/7-2/ubuntu22.04/meta.json, release/7-2/ubuntu22.04/test-deps/docker/Dockerfile, release/7-2/ubuntu22.04/test-deps/meta.json, release/7-3/ubuntu22.04/docker/Dockerfile, release/7-3/ubuntu22.04/meta.json, release/7-3/ubuntu22.04/test-deps/docker/Dockerfile, release/7-3/ubuntu22.04/test-deps/meta.json
Update:
libssl1.1 -> libssl3
libicu66 -> libicu70
liblttng-ust0 -> liblttng-ust1
=> Add support for Ubuntu22.04

build.ps1
=> Add tags to matrix JSONs

build.ps1, release/7-2/mariner2/docker/Dockerfile, release/7-3/alpine313/meta.json, release/7-3/alpine314/meta.json, release/7-3/arm32v7/meta.json, release/7-3/mariner2/docker/Dockerfile, release/7-3/ubuntu20.04/meta.json, tests/container.tests.ps1, tools/buildHelper/buildHelper.psm1
- Add metadata to JSON to control images that will run in CI
- Mark images that can't run in CI, such as alpine and ARM images not to run in CI.
- Fix Mariner images because a package was removed from preview.
=> Add metadata to JSON to control images that will run in CI

.vsts-ci/build-ps1-unittests/buildUnitTests.yml, .vsts-ci/phase.yml, build.ps1, tools/buildHelper/buildHelper.psm1, unittests/build.tests.ps1, unittests/generateMatrixJson.tests.ps1
=> Add Component Governance

.vsts-ci/phase.yml, .vsts-ci/releasePhase.yml, .vsts-ci/releasePipeline.yml, .vsts-ci/releasebuild.yml
=> Run Component Governance during release

release/7-2/ubuntu20.04/test-deps/meta.json, release/7-3/alpine315/docker/Dockerfile, release/7-3/alpine315/meta.json, release/7-3/alpine315/test-deps/docker/Dockerfile, release/7-3/alpine315/test-deps/meta.json
=> Add support for alpine 3.15

release/7-2/mariner2/meta.json, release/7-2/mariner2/test-deps/meta.json, release/7-2/ubuntu22.04/meta.json, release/7-3/ubuntu22.04/meta.json
=> Mark Ubuntu 22.04 as validated

release/7-2/mariner2/docker/Dockerfile, release/7-2/mariner2/meta.json, release/7-2/mariner2/test-deps/docker/Dockerfile, release/7-2/mariner2/test-deps/meta.json, release/7-3/mariner2/docker/Dockerfile, release/7-3/mariner2/test-deps/docker/Dockerfile, release/7-3/mariner2/test-deps/meta.json
=> Update to GA mariner 2.0 images

build.ps1, tools/buildHelper/buildHelper.psm1
=> Make matrix JSON consistent

.github/workflows/update.yml, tools/updateJson.ps1
=> Only update matrix JSON if there is a diff

release/7-2/mariner2/test-deps/docker/Dockerfile, release/7-3/mariner2/test-deps/docker/Dockerfile
=> Add tar to mariner stable

build.ps1, release/7-3/mariner2/docker/Dockerfile, release/7-3/mariner2/meta.json
=> Make mariner use rpm file

release/7-2/mariner2/docker/Dockerfile, release/7-2/mariner2/meta.json, release/7-2/mariner2/test-deps/docker/Dockerfile, release/7-3/mariner2/docker/Dockerfile, release/7-3/mariner2/meta.json, release/7-3/mariner2/test-deps/docker/Dockerfile
=> Update mariner images for PowerShell 7.2.5 release

release/7-2/alpine313/meta.json, release/7-2/alpine314/meta.json, release/7-2/mariner2/test-deps/docker/Dockerfile, release/7-3/alpine313/meta.json, release/7-3/alpine314/meta.json, release/7-3/mariner2/test-deps/docker/Dockerfile
* Also update stable Alpine image sizes
[Release CBL-Mariner 2.0 July 2022 Update · microsoft/CBL-Mariner (github.com)](https://github.com/microsoft/CBL-Mariner/releases/tag/2.0.20220713-2.0)
[Release Release 4.10 · shadow-maint/shadow (github.com)](https://github.com/shadow-maint/shadow/releases/tag/v4.10)
=> Add SU to mariner

release/7-2/alpine313/meta.json, release/7-2/alpine314/meta.json, release/7-2/ubuntu18.04-arm32v7/meta.json, release/7-2/ubuntu20.04-arm32v7/meta.json, release/7-2/ubuntu22.04-arm32v7/meta.json, release/7-3/ubuntu20.04-arm32v7/meta.json, release/7-3/ubuntu22.04-arm32v7/meta.json
Mark Arm and alpine images as not to be used in CI
=> Mark arm images and alpine images to not be used in CI

tests/containerTestCommon.psm1
=> Update docker host detection

release/7-2/alpine313/docker/Dockerfile, release/7-2/alpine313/test-deps/docker/Dockerfile, release/7-2/alpine314/docker/Dockerfile, release/7-2/alpine314/test-deps/docker/Dockerfile, release/7-3/alpine313/docker/Dockerfile, release/7-3/alpine313/test-deps/docker/Dockerfile, release/7-3/alpine314/docker/Dockerfile, release/7-3/alpine314/test-deps/docker/Dockerfile, release/7-3/alpine315/docker/Dockerfile, release/7-3/alpine315/test-deps/docker/Dockerfile, tests/container.tests.ps1
Use alpine node package
*  Also, Upgrade installed packages
=> Use alpine node package

.vsts-ci/releasePhase.yml, .vsts-ci/releaseStage.yml
- pin to old image version
- fix syntax
=> Pin Windows release build image version

tests/containerTestCommon.psm1
Use az.cmd in release build because the az cli introduced breaking change in az.ps1
=> Use az.cmd in release build

.vsts-ci/phase.yml
- move ubuntu arm image back
- Add ARM build to CI
=> Enable Component Governance on ARM64

release/7-3/alpine313/docker/Dockerfile, release/7-3/alpine313/meta.json, release/7-3/alpine314/docker/Dockerfile, release/7-3/alpine314/meta.json, release/7-3/alpine315/docker/Dockerfile, release/7-3/alpine315/meta.json, release/7-3/debian10/docker/Dockerfile, release/7-3/debian10/meta.json, release/7-3/debian10/test-deps/meta.json, release/7-3/debian11/docker/Dockerfile, release/7-3/debian11/meta.json, release/7-3/debian11/test-deps/meta.json, release/7-3/mariner2/docker/Dockerfile, release/7-3/mariner2/meta.json, release/7-3/ubi8/docker/Dockerfile, release/7-3/ubi8/meta.json, release/7-3/ubi9/docker/Dockerfile, release/7-3/ubi9/meta.json, release/7-3/ubi9/test-deps/meta.json, release/7-3/ubuntu20.04/docker/Dockerfile, release/7-3/ubuntu20.04/meta.json, release/7-3/ubuntu20.04/test-deps/meta.json, release/7-3/ubuntu22.04/docker/Dockerfile, release/7-3/ubuntu22.04/meta.json, tests/container.tests.ps1
Update image sizes for preview images and remove -Pending from respective test.
=> Update preview image size

.vsts-ci/phase.yml
Component Governance should be supported on Ubuntu for arm64, so remove pwsh code for it.
=> remove arm component governance pwsh code 

tools/buildHelper/channels.json
=> Promote 7-3 to stable

.vsts-ci/phase.yml, release/7-3/mariner2-arm64/docker/Dockerfile, release/7-3/mariner2-arm64/meta.json
=> add mariner arm64 image

release/7-3/alpine314/docker/Dockerfile, release/7-3/alpine315/docker/Dockerfile, release/7-3/debian11/docker/Dockerfile, release/7-3/ubuntu20.04-arm32v7/docker/Dockerfile, release/7-3/ubuntu20.04/docker/Dockerfile, release/7-3/ubuntu22.04-arm32v7/docker/Dockerfile, release/7-3/ubuntu22.04/docker/Dockerfile, release/7-4/alpine314/docker/Dockerfile, release/7-4/alpine315/docker/Dockerfile, release/7-4/debian11/docker/Dockerfile, release/7-4/ubuntu20.04-arm32v7/docker/Dockerfile, release/7-4/ubuntu20.04/docker/Dockerfile, release/7-4/ubuntu22.04-arm32v7/docker/Dockerfile, release/7-4/ubuntu22.04/docker/Dockerfile
=> Start using ACR pull-through caching for dockerHub

.github/workflows/scorecard.yml
=> Create scorecard workflow

.vsts-ci/templatesReleasePipeline/testStage.yml
=> Add job for linux arm tests during release

release/7-4/mariner2-arm64/docker/Dockerfile, release/7-4/mariner2-arm64/meta.json
Add image for mariner arm64 preview
=> Add Mariner arm64 preview image

release/7-2/alpine316/docker/Dockerfile, release/7-2/alpine316/meta.json, release/7-2/alpine316/test-deps/docker/Dockerfile, release/7-2/alpine316/test-deps/meta.json, release/7-2/alpine317/docker/Dockerfile, release/7-2/alpine317/meta.json, release/7-2/alpine317/test-deps/docker/Dockerfile, release/7-2/alpine317/test-deps/meta.json, release/7-3/alpine316/docker/Dockerfile, release/7-3/alpine316/meta.json, release/7-3/alpine316/test-deps/docker/Dockerfile, release/7-3/alpine316/test-deps/meta.json, release/7-3/alpine317/docker/Dockerfile, release/7-3/alpine317/meta.json, release/7-3/alpine317/test-deps/docker/Dockerfile, release/7-3/alpine317/test-deps/meta.json, release/7-4/alpine316/docker/Dockerfile, release/7-4/alpine316/meta.json, release/7-4/alpine316/test-deps/docker/Dockerfile, release/7-4/alpine316/test-deps/meta.json, release/7-4/alpine317/docker/Dockerfile, release/7-4/alpine317/meta.json, release/7-4/alpine317/test-deps/docker/Dockerfile, release/7-4/alpine317/test-deps/meta.json
=> Add alpine 3.16 and 3.17

.vsts-ci/releaseStage.yml
ACR reduced the concurrent builds we can run.
ACR is only used to build windows
=> Reduce the concurrent ACR builds

release/7-3/debian12/docker/Dockerfile, release/7-3/debian12/meta.json, release/7-3/debian12/test-deps/docker/Dockerfile, release/7-3/debian12/test-deps/meta.json, release/7-3/mariner2/meta.json, release/7-4/debian12/docker/Dockerfile, release/7-4/debian12/meta.json, release/7-4/debian12/test-deps/docker/Dockerfile, release/7-4/debian12/test-deps/meta.json, release/7-4/mariner2/meta.json
=> Add images for Debian12

release/7-4/debian12/meta.json
Image is built, start using it in CI
=> Revert "Don't use debian 12 in CI until it is built"

docs/MAINTAINERS, docs/README.powershell.md, docs/development.md
=> fixing of grammar

release/7-4/mariner2/test-deps/docker/Dockerfile
Don't upgrade to newest preview in test-deps
=> Don't upgrade to newest preview in test-deps

release/7-4/alpine317/docker/Dockerfile, release/7-4/alpine317/test-deps/docker/Dockerfile
see https://github.com/dotnet/dotnet-docker/issues/3844
the full set of locales is not installed by default
=> Add icu-dev and icu-data-full to make sure we have all the locales installed

tools/buildHelper/buildHelper.psm1
=> Remove EOL from distribution info in JSON

.vsts-ci/releasePhase.yml, tools/buildHelper/channels.json
=> Update channels for 7.4 GA

release/7-5/mariner2-arm64/docker/Dockerfile, release/7-5/mariner2/docker/Dockerfile
=> Sync Mariner changes from 7-4 to 7-5

release/7-5/mariner2-arm64/docker/Dockerfile
updated version as well to test the change
=> Fix typo in docker stage name

release/7-3/mariner2-arm64/meta.json, release/7-4/mariner2-arm64/meta.json, release/7-5/mariner2-arm64/meta.json, release/7-5/mariner2/docker/Dockerfile
- Update the metadata json so that it does not pass the package URL as base64 encoded. 
- Remove the UserACR as the default value is false.
=> Update meta.json for mariner2-arm64

vsts-ci.yml
=> exclude channel based ReleaseStage.yml files from ci

.vsts-ci/ltsReleaseStage.yml, .vsts-ci/previewReleaseStage.yml, .vsts-ci/stableReleaseStage.yml, tools/buildHelper/buildHelper.psm1
artifactSuffix is used to create jobName in build and thus cant have a period in it
=> Remove Period from artifactSuffix in Channel Based ReleaseStage.yml

.vsts-ci/ltsReleaseStage.yml, tools/buildHelper/buildHelper.psm1
Specify 2022 pooled job for all windows jobs, including nanoserver1809 as 2022 pooled job is backwards compatible
=> Specify 2022 pooled job for all windows jobs

.vsts-ci/ltsReleaseStage.yml, .vsts-ci/previewReleaseStage.yml, .vsts-ci/stableReleaseStage.yml, tools/buildHelper/buildHelper.psm1
=> Update BuildHelper to rename the releasePhase.yml file to releaseJob.yml

.pipelines/PowerShell-Docker-Image-Build-Official.yml
BuildInfo.json file will contain channel and release version tag fields for release to use.
=> Update OneBranch build to output artifact with buildInfo.json

.github/CODE_OF_CONDUCT.md, .github/SECURITY.md, README.md, docs/SECURITY.md
Updates the readme, code of conduct and security policy per OSPO request.
Wasn't quite sure what to do with `docs/SECURITY.md` but updated it to point to the official document.
=> Update Code of Conduct and Security Policy

release/7-5/ubi8/meta.json
=> update size for ubi8 for preview

release/7-5/ubi8/meta.json
increase size for ubi8 image in tests for preview
=> increase size for ubi8 for preview

release/7-5/azurelinux3/meta.json, release/7-5/debian12/meta.json, release/7-5/ubuntu24.04/meta.json
Remove images from CI which dont have test deps images yet.
=> Disable new images from being used in CI

release/7-5/debian12/meta.json
=> Enable Debian12 in CI

.vsts-ci/releaseJob.yml
=> Pass AFD through the existing SASUrl code

.pipelines/PowerShell-Docker-Image-Build-Official.yml, .pipelines/PowerShell-Docker-Image-Release-Official.yml, .vsts-ci/releaseJob.yml
Use Ubuntu instead of mariner as the host image for OBP docker build task, this is due to a bug OBP is fixing.
Also remove ACR Login task as that was failing silently before but not silently anymore.
=> Use Ubuntu host image

.vsts-ci/releaseJob.yml, tools/buildHelper/buildHelper.psm1
Fix how the package Url is created given a Sas Url.
=> Bugfix for how package Url is created

release/7-4/alpine320/docker/Dockerfile, release/7-4/alpine320/meta.json, release/7-4/alpine320/test-deps/docker/Dockerfile, release/7-4/alpine320/test-deps/meta.json, release/7-5/alpine320/docker/Dockerfile, release/7-5/alpine320/meta.json, release/7-5/alpine320/test-deps/docker/Dockerfile, release/7-5/alpine320/test-deps/meta.json
=> Add support for Alpine 3.20

.vsts-ci/previewReleaseStage.yml, .vsts-ci/stableReleaseStage.yml
Update build yaml files by running updateBuildYamls.ps1, to include newly supported distros like alpine320, azurelinux3, ubuntu24.04, and azurelinux3-arm64.
=> Update build yaml files with newly added distros

release/7-5/ubuntu24.04/meta.json, release/7-6/ubuntu24.04/meta.json
Increase expected size of Ubuntu 24.0 preview image for size test
=> Increase expected size of Ubuntu 24.0 preview image for size test
