- README.md
With docker 1.12, docker build fails with the above error for Dockerfiles that use `ARG` before `FROM`.
> Avoid Please provide a source image with `from` prior to commit.

- release/stable/windowsservercore/docker/Dockerfile
Remove version verification for Windows Server Core
- version verification is now done post build and the script quit working
- add the missing VCS_REF arg noticed when debugging this issue
> Remove version verification for Windows Server Core

- assets/README.powershell.md
- createAllManifests.ps1
make `latest` use Ubuntu 18.04 instead of 16.04
- update readme to that effect
- **OR**
> make `latest` use Ubuntu 18.04 instead of 16.04

- release/preview/fedora27/docker/Dockerfile
- release/preview/fedora28/docker/Dockerfile
- release/stable/fedora27/docker/Dockerfile
- release/stable/fedora28/docker/Dockerfile
`PS_VERSION` in Dockerfiles for Fedora images are different
from other images.
```
$ grep PS_VERSION= release/*/*/*/Dockerfile
release/preview/alpine/docker/Dockerfile:ARG PS_VERSION=6.1.0-rc.1
release/preview/alpine/docker/Dockerfile:ARG PS_VERSION=6.1.0-rc.1
release/preview/centos7/docker/Dockerfile:ARG PS_VERSION=6.1.0~rc.1
release/preview/fedora27/docker/Dockerfile:ARG PS_VERSION=6.0.4
release/preview/fedora28/docker/Dockerfile:ARG PS_VERSION=6.0.4
release/preview/nanoserver/docker/Dockerfile:ARG PS_VERSION=6.1.0-rc.1
release/preview/nanoserver/docker/Dockerfile:ARG PS_VERSION=6.1.0-rc.1
release/preview/ubuntu14.04/docker/Dockerfile:ARG PS_VERSION=6.1.0~rc.1
release/preview/ubuntu16.04/docker/Dockerfile:ARG PS_VERSION=6.1.0~rc.1
release/preview/ubuntu18.04/docker/Dockerfile:ARG …
```
> Fix PS_VERSION in Fedora images

- release/preview/alpine/docker/Dockerfile
- release/preview/centos7/docker/Dockerfile
- release/preview/fedora27/docker/Dockerfile
- release/preview/fedora28/docker/Dockerfile
- release/preview/ubuntu14.04/docker/Dockerfile
- release/preview/ubuntu16.04/docker/Dockerfile
- release/preview/ubuntu18.04/docker/Dockerfile
- release/servicing/centos7/docker/Dockerfile
- release/servicing/fedora27/docker/Dockerfile
- release/servicing/ubuntu14.04/docker/Dockerfile
- release/servicing/ubuntu16.04/docker/Dockerfile
- release/stable/alpine/docker/Dockerfile
- release/stable/centos7/docker/Dockerfile
- release/stable/debian8/docker/Dockerfile
- release/stable/debian9/docker/Dockerfile
- release/stable/fedora27/docker/Dockerfile
- release/stable/fedora28/docker/Dockerfile
- release/stable/opensuse423/docker/Dockerfile
- release/stable/ubuntu14.04/docker/Dockerfile
- release/stable/ubuntu16.04/docker/Dockerfile
- release/stable/ubuntu18.04/docker/Dockerfile
On Linux systems, PowerShell's `help` command relies on `less` command
but currently it is not installed.
This commit adds `less` package to Linux images.
- **OR**
> Add "less" package to Linux images for "help" command

- release/servicing/centos7/docker/Dockerfile
- release/servicing/fedora27/docker/Dockerfile
- release/servicing/ubuntu16.04/docker/Dockerfile
- release/stable/centos7/docker/Dockerfile
- release/stable/fedora27/docker/Dockerfile
- release/stable/fedora28/docker/Dockerfile
- release/stable/ubuntu16.04/docker/Dockerfile
- release/stable/ubuntu18.04/docker/Dockerfile
- tests/containerTestCommon.psm1
- vsts-ci.yml
Make images use package files from Github
- Stable and Servicing RedHat variants 
- All preview images are blocked due to inconsistency with the package name
- Enable CI for Stable Ubuntu 18.04 and Fedora 28
- **OR**
> Make images use package files from Github

- release/preview/alpine/docker/Dockerfile
- release/servicing/centos7/docker/Dockerfile
- release/servicing/fedora27/docker/Dockerfile
- release/servicing/ubuntu14.04/docker/Dockerfile
- release/servicing/ubuntu16.04/docker/Dockerfile
- release/stable/alpine/docker/Dockerfile
- release/stable/centos7/docker/Dockerfile
- release/stable/fedora27/docker/Dockerfile
- release/stable/fedora28/docker/Dockerfile
- release/stable/opensuse423/docker/Dockerfile
- release/stable/ubuntu14.04/docker/Dockerfile
- release/stable/ubuntu16.04/docker/Dockerfile
- release/stable/ubuntu18.04/docker/Dockerfile
Make Ubuntu 14.04 stable and servicing to using packages download instead of packages.microsoft.com
- **OR**
> Make Ubuntu 14.04 stable and servicing to using packages download instead of packages.microsoft.com

- release/stable/debian8/docker/Dockerfile
- release/stable/debian9/docker/Dockerfile
- tests/containerTestCommon.psm1
Make Debian 8 and 9 to using packages download instead of packages.microsoft.com
- **OR**
> Make Debian 8 and 9 to using packages download instead of packages.microsoft.com

- release/preview/alpine/docker/Dockerfile
- tests/container.tests.ps1
- vsts-ci.yml
6.2p1 build failed due to the refactoring of the native code out of the powershell/powershell repo
- **OR**
> Update alpine preview to use 6.1.0 tar gz

- build.ps1
- release/preview/centos7/docker/Dockerfile
- release/preview/fedora27/docker/Dockerfile
- release/preview/fedora28/docker/Dockerfile
- release/preview/nanoserver/meta.json
- release/servicing/nanoserver/meta.json
- release/stable/nanoserver/meta.json
- tests/container.tests.ps1
Fix RPM and NanoServer package formats
- RPM has an underscore after the version number if it is a preview
- NanoServer uses a zip and not MSI
- **OR**
> Fix RPM and nanoserver package formats

- build.ps1
- release/community-stable/amazonlinux/getLatestTag.ps1
Fix build issues caused by a bad getTags script
- fix the build script to warn when it gets a missing fullTag in a get tags result
- fix the amazonlinux image to correctly return tags
- **OR**
> Fix build issues caused by a bad getTags script

- release/preview/alpine/docker/Dockerfile
`docker build` for Alpine is broken because the PowerShell team superseded Alpine preview.2 tgz with preview.3 release (no longer previous preview files distributed). Simply targeting on preview.3 fixes this issue.
Related: #97 
- **OR**
> Fix Alpine build

- .vsts-ci/phase.yml
- createAllManifests.ps1
- vsts-ci.yml
Update manifest for 1809
- manifests are `preview`, `latest` and `nanoserver`
- Also, add the ability to specify that some phases can just ignore all errors to temporarily deal with #112 and #113
- **OR**
> Update manifest for 1809

- build.ps1
fix issue where release build URLs are not calculated correctly
- **OR**
> fix issue where release build URLs are not calculated correctly

- .vsts-ci/phase.yml
- build.ps1
- release/preview/nanoserver/meta.json
- release/preview/nanoserver/tags.json
- release/servicing/nanoserver/meta.json
- release/servicing/nanoserver/tags.json
- release/stable/nanoserver/getLatestTag.ps1
- release/stable/nanoserver/meta.json
- release/stable/nanoserver/tags.json
- tools/buildHelper/buildHelper.psm1
Add know issue metadata to allow skipping from tags which we know don't work
- Also, allow `tags.json` to be moved into `meta.json`
- **OR**
> Add know issue metadata to allow skipping from tags which we know don't work

- release/preview/nanoserver/getLatestTag.ps1
- release/preview/nanoserver/meta.json
- release/preview/nanoserver1809/docker/Dockerfile
- release/preview/nanoserver1809/getLatestTag.ps1
- release/preview/nanoserver1809/meta.json
- release/servicing/nanoserver/docker/Dockerfile
- release/servicing/nanoserver/getLatestTag.ps1
- release/servicing/nanoserver/meta.json
- release/servicing/nanoserver1809/docker/Dockerfile
- release/servicing/nanoserver1809/getLatestTag.ps1
- release/servicing/nanoserver1809/meta.json
- release/stable/nanoserver/getLatestTag.ps1
- release/stable/nanoserver/meta.json
- release/stable/nanoserver1809/docker/Dockerfile
- release/stable/nanoserver1809/getLatestTag.ps1
- release/stable/nanoserver1809/meta.json
Separate `nanoserver 1809` due to breaking change
- `SETX` no longer works to set environment variable so 1809 has to be separate at least from `1709` where `ENV` did not work for the `PATH` variable.
- Also fix regex for `nanoserver` tag query
Fixes #89 
- **OR**
> Separate `nanoserver 1809` due to breaking change

- release/preview/debian9/getLatestTag.ps1
- release/stable/debian9/getLatestTag.ps1
Change the short tag for Debian 9 to 9 instead of 8
- **OR**
> Change the short tag for Debian 9 to 9 instead of 8

- tests/container.tests.ps1
Fix Windows Pull test cases beforeAll variable initialization
- **OR**
> Fix Windows Pull test cases beforeAll variable initialization

- .poshchan/settings.json
Update settings to new format that allows configuring azdevops org/project and separate permissions for builds vs reminders
- **OR**
> update settings for poshchan-bot

- release/preview/opensuse423/docker/Dockerfile
- release/servicing/opensuse423/docker/Dockerfile
- release/stable/opensuse423/docker/Dockerfile
make sure all users have permissions to execute pwsh on openSUSE
- **OR**
> make sure all users have permissions to execute pwsh on openSUSE

- release/community-stable/amazonlinux/docker/Dockerfile
- release/community-stable/oraclelinux/docker/Dockerfile
- release/preview/centos7/docker/Dockerfile
- release/preview/fedora28/docker/Dockerfile
- release/servicing/centos7/docker/Dockerfile
- release/servicing/fedora28/docker/Dockerfile
- release/stable/centos7/docker/Dockerfile
- release/stable/fedora28/docker/Dockerfile
This patch uses the included curl on RedHat-based distro images to download PowerShell in the same layer it's installed in. This slices off one layer from the resulting images and saves ~50 MB (the size of the PowerShell dist package) on final image size.
- **OR**
> Download, install, and delete pwsh dist in the same layer to reduce final image size (RedHat family-only)

- release/community-stable/amazonlinux/test-deps/docker/Dockerfile
- release/preview/alpine/test-deps/docker/Dockerfile
- release/preview/centos7/docker/Dockerfile
- release/preview/centos7/test-deps/docker/Dockerfile
- release/preview/debian9/test-deps/docker/Dockerfile
- release/preview/fedora28/docker/Dockerfile
- release/preview/fedora28/test-deps/docker/Dockerfile
- release/preview/opensuse423/test-deps/docker/Dockerfile
- release/preview/ubuntu16.04/test-deps/docker/Dockerfile
- release/preview/ubuntu18.04/test-deps/docker/Dockerfile
- release/stable/alpine/test-deps/docker/Dockerfile
- release/stable/centos7/docker/Dockerfile
- release/stable/centos7/test-deps/docker/Dockerfile
- release/stable/debian9/test-deps/docker/Dockerfile
- release/stable/fedora28/test-deps/docker/Dockerfile
- release/stable/opensuse423/test-deps/docker/Dockerfile
- release/stable/ubuntu16.04/test-deps/docker/Dockerfile
- release/stable/ubuntu18.04/test-deps/docker/Dockerfile
- tests/container.tests.ps1
- tests/containerTestCommon.psm1
- vsts-ci.yml
`tar` is required to extract the test artifacts for release automation tests. OpenSUSE does not have tar in its base image.
- **OR**
> Add `tar` to the test dependencies

- README.md
Followup to my other PR: #208 
- **OR**
> Readme: Bump Ubuntu versions

- release/preview/nanoserver/docker/Dockerfile
- release/preview/nanoserver1809/docker/Dockerfile
- release/servicing/nanoserver/docker/Dockerfile
- release/servicing/nanoserver1809/docker/Dockerfile
- release/stable/nanoserver/docker/Dockerfile
- release/stable/nanoserver1809/docker/Dockerfile
- vsts-ci.yml
Use the PowerShell Nano Server image to build nanoserver
ServerCore broke us by changing their tags.  Using nanoserver is faster and should be more reliable.
- **OR**
> Use the PowerShell Nanoserver image to build nanoserver

- release/community-stable/archlinux/docker/Dockerfile
- release/community-stable/blackarch/docker/Dockerfile
- release/community-stable/parrot/docker/Dockerfile
- release/community-stable/photon/docker/Dockerfile
- release/preview/alpine/docker/Dockerfile
- release/preview/opensuse423/docker/Dockerfile
- release/servicing/alpine/docker/Dockerfile
- release/servicing/opensuse423/docker/Dockerfile
- release/stable/alpine/docker/Dockerfile
- release/stable/opensuse423/docker/Dockerfile
- tests/container.tests.ps1
Remove write permission for others in tar installed images
- Also, add tests to verify this for all Linux images
- **OR**
> Remove write permission for others in tar installed images

- release/preview/alpine/test-deps/docker/Dockerfile
- release/stable/alpine/test-deps/docker/Dockerfile
Alpine fails in Azure DevOps due to warning "(node:76) Warning: Use Cipheriv for counter mode of aes-256-ctr". 
This PR disables displaying warnings. Only the test-deps images are updated.
- **OR**
> Add workaround to enable Alpine runs in Azure DevOps for testdeps images

- release/preview/nanoserver/docker/Dockerfile
- release/preview/nanoserver1809/docker/Dockerfile
- release/preview/windowsservercore/docker/Dockerfile
- release/servicing/nanoserver/docker/Dockerfile
- release/servicing/nanoserver1809/docker/Dockerfile
- release/servicing/windowsservercore/docker/Dockerfile
- release/stable/nanoserver/docker/Dockerfile
- release/stable/nanoserver1809/docker/Dockerfile
- release/stable/windowsservercore/docker/Dockerfile
Add semicolon to the end of the windows path
fixes #228 
- **OR**
> Add semicolon to the end of the windows path

- release/stable/arm32v7/docker/Dockerfile
Updated Dockerfile to the latest release
- [ X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X ] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ X] This PR is ready to merge and is not [Work in …
> Update Dockerfile for arm image

- createAllManifests.ps1
- release/preview/nanoserver/meta.json
- release/preview/nanoserver1809/getLatestTag.ps1
- release/preview/nanoserver1809/meta.json
- release/preview/windowsservercore/getLatestTag.ps1
- release/stable/nanoserver/meta.json
- release/stable/nanoserver1809/getLatestTag.ps1
- release/stable/nanoserver1809/meta.json
- release/stable/windowsservercore/getLatestTag.ps1
- tools/getDockerTags/getDockerTags.psm1
- vsts-ci.yml
Add 1903 to WindowsServerCore and nanoserver
remove 1709 from both
fixes #238 
- **OR**
> Add 1903 build based on 1809

- .dependabot/config.yml
- release/preview/alpine/dependabot/Dockerfile
- release/preview/centos7/dependabot/Dockerfile
- release/preview/debian9/dependabot/Dockerfile
- release/preview/fedora28/dependabot/Dockerfile
- release/preview/nanoserver1809/dependabot/Dockerfile
- release/preview/opensuse423/dependabot/Dockerfile
- release/preview/ubuntu18.04/dependabot/Dockerfile
- release/preview/windowsservercore/dependabot/Dockerfile
Will cause dependabot to submit PRs when we need to update the images.  
We will have to actually update the image, but at least we will get a notice.
Addresses #240 
- **OR**
> Add files to cause dependabot to open PRs

- release/community-stable/archlinux/docker/Dockerfile
- release/preview/alpine38/docker/Dockerfile
- release/preview/alpine39/docker/Dockerfile
- release/preview/opensuse423/docker/Dockerfile
- release/stable/alpine/docker/Dockerfile
- release/stable/opensuse423/docker/Dockerfile
> Add verbose switch to tar commands

- release/preview/debian10/dependabot/Dockerfile
- release/preview/debian10/docker/Dockerfile
- release/preview/debian10/getLatestTag.ps1
- release/preview/debian10/meta.json
- release/preview/debian10/test-deps/docker/Dockerfile
- release/preview/debian10/test-deps/meta.json
- vsts-ci.yml
Add Debian 10 experimental preview image
- **OR**
> Add Debian 10

- release/community-stable/archlinux/docker/Dockerfile
- vsts-ci.yml
Fix #280 
- Update PowerShell version to 6.2.3
https://github.com/PowerShell/PowerShell-Docker/blob/1675dfe44a3df9bb4e71fd2464b9e86cf7ef9a90/release/community-stable/archlinux/docker/Dockerfile#L14
- Remove folder structure since updated container base image fixed the missing folder
https://github.com/PowerShell/PowerShell-Docker/blob/1675dfe44a3df9bb4e71fd2464b9e86cf7ef9a90/release/community-stable/archlinux/docker/Dockerfile#L80-L82
- **OR**
> Fix ArchLinux failing

- release/community-stable/blackarch/docker/Dockerfile
- vsts-ci.yml
Fix #282 
- Update PowerShell version to 6.2.3
https://github.com/PowerShell/PowerShell-Docker/blob/1675dfe44a3df9bb4e71fd2464b9e86cf7ef9a90/release/community-stable/blackarch/docker/Dockerfile#L21
- Remove folder structure since updated container base image fixed the missing folder
https://github.com/PowerShell/PowerShell-Docker/blob/1675dfe44a3df9bb4e71fd2464b9e86cf7ef9a90/release/community-stable/blackarch/docker/Dockerfile#L95-L97
- **OR**
> Fix BlackArch failing

- release/community-stable/parrot/docker/Dockerfile
- release/community-stable/parrot/getLatestTag.ps1
- vsts-ci.yml
fix #289 
- Update Base Container image from 4.4 to latest tag
- Update PowerShell version from 6.1.0 to 6.2.3
- Update libicu57_57.1 package source url and filename
- **OR**
> Fix ParrotSec failing

- release/community-stable/blackarch/docker/Dockerfile
- release/community-stable/blackarch/meta.json
add support to #124 
remediate issue found in PR #284 
- Create multi-stage builds Dockerfile for BlackArch
- Stage 1 Build - [gss-ntlmssp](https://aur.archlinux.org/packages/gss-ntlmssp/)
- use `pacman` to install developer packages
- use `git clone https://aur.archlinux.org/gss-ntlmssp.git` clone repository
- use `makepkg` to build the gss-ntlmssp package
- Stage 2 Installation
- copy gss-ntlmssp package from previous stage
- use `pacman -U` to install the gas-ntlmssp package
- ...the rest remains the same...
- **OR**
> Add NTLM remoting to BlackArch using multi-stage builds

- README.md
- assets/README.powershell.md
As seen on the docker hub Powershell page and as per [other blog posts](https://techcommunity.microsoft.com/t5/Containers/Windows-Server-2019-Now-Available/ba-p/382430), MCR is the defect registry for images. Otherwise this doesn't align with all the other doco, including the docker hub page which links here.
- **OR**
> MCR is the defacto source for images

- release/community-stable/amazonlinux/docker/Dockerfile
- release/community-stable/amazonlinux/getLatestTag.ps1
- release/community-stable/amazonlinux/meta.json
- Fix #297 
- Revisit Merged PR #184
- Add Support #124
- Update AmazonLinux Image Tag to Latest
- Update PowerShell version to 6.2.3
- Fix on how to add EPEL repository to YUM (package manager) in AmazonLinux environment
- Install `gssntlmssp` package from EPEL repository
- Set `SkipGssNtlmSspTests` from `true` to `false`
- **OR**
> Add NTLM remoting to AmazonLinux

- release/preview/fedora/docker/Dockerfile
Fix fedora security updating
- FEDORA-2019-27e7b92407 had to be completely manually installed
- FEDORA-2019-3377813d18 had to be installed by advisory name
- **OR**
> Fix fedora security updating

- .vsts-ci/phase.yml
- .vsts-ci/releasePhase.yml
- .vsts-ci/releaseStage.yml
- .vsts-ci/releasebuild.yml
Convert release build to use generated matrix
This will make it easier to add LTS
This also has the benefit that each image is not individually retry-able. 
- **OR**
> Convert release build to use generated matrix

- release/preview/centos8/docker/Dockerfile
on CentOS some tests fail because clear doesn't work. adding ncurses to the image so it does.
- **OR**
> Add ncurses to the image so clear works

- .dependabot/config.yml
- .vsts-ci/releasePhase.yml
- .vsts-ci/releaseStage.yml
- .vsts-ci/releasebuild.yml
- release/lts/debian11/test-deps/meta.json
- release/preview/debian11/test-deps/meta.json
- release/preview/ubuntu18.04/dependabot/Dockerfile
- release/preview/ubuntu20.04/docker/Dockerfile
- release/preview/ubuntu20.04/meta.json
- release/preview/ubuntu20.04/test-deps/docker/Dockerfile
- release/preview/ubuntu20.04/test-deps/meta.json
- release/stable/debian11/test-deps/meta.json
- tools/buildHelper/buildHelper.psm1
- tools/getDockerTags/getDockerTags.psm1
Add Ubuntu 20.04
This also starts using our own full tag for that image
cc @RDIL 
Requirements for that
* from tag must be defined in docker file
* short tags must be in the meta.json
* tag formats must be in meta.json
* the script to generate the tags must **not** exist
- **OR**
> Add Ubuntu 20.04

- release/lts/alpine38/dependabot/Dockerfile
- release/lts/alpine38/test-deps/docker/Dockerfile
- release/lts/alpine38/test-deps/meta.json
- release/lts/alpine39/test-deps/docker/Dockerfile
- release/lts/alpine39/test-deps/meta.json
- release/preview/alpine311/test-deps/docker/Dockerfile
- release/preview/alpine311/test-deps/meta.json
- release/preview/alpine38/dependabot/Dockerfile
- release/preview/alpine38/test-deps/docker/Dockerfile
- release/preview/alpine38/test-deps/meta.json
- release/preview/alpine39/test-deps/docker/Dockerfile
- release/preview/alpine39/test-deps/meta.json
- release/stable/alpine38/dependabot/Dockerfile
- release/stable/alpine38/test-deps/docker/Dockerfile
- release/stable/alpine38/test-deps/meta.json
- release/stable/alpine39/test-deps/docker/Dockerfile
- release/stable/alpine39/test-deps/meta.json
Signed-off-by: Reece Dunham <me@rdil.rocks>
Node 10 goes EOL soon and dependabot keeps bugging everybody about this so I think its time to update.  
- **OR**
> Update node to v14

- .github/PULL_REQUEST_TEMPLATE.md
- release/lts/nanoserver1809/dependabot/Dockerfile
- release/lts/nanoserver1809/meta.json
- release/lts/windowsservercore/dependabot/Dockerfile
- release/lts/windowsservercore/getLatestTag.ps1
- release/preview/nanoserver1809/dependabot/Dockerfile
- release/preview/nanoserver1809/meta.json
- release/preview/windowsservercore/dependabot/Dockerfile
- release/preview/windowsservercore/getLatestTag.ps1
- release/preview/windowsservercore/meta.json
- release/servicing/nanoserver1809/meta.json
- release/servicing/windowsservercore/getLatestTag.ps1
- release/stable/nanoserver1809/meta.json
- release/stable/windowsservercore/getLatestTag.ps1
This adds Windows 2004 releases to all the lists, and Windows 1909 to a
few lists from which it was missing.
This should replace #436, the Dependabot reminder that Windows 2004 is now available.
- Nothing in this for Windows versions
- Nothing apparent that needs updating.
> Ensure coverage of all active Windows releases

- release/community-stable/amazonlinux/docker/Dockerfile
- release/community-stable/archlinux/docker/Dockerfile
- release/community-stable/blackarch/docker/Dockerfile
- release/community-stable/clearlinux/docker/Dockerfile
- release/community-stable/kalilinux/docker/Dockerfile
- release/community-stable/parrotsec/docker/Dockerfile
- release/community-stable/photon/docker/Dockerfile
- release/unstable/oraclelinux/docker/Dockerfile
1. Addresses #374 enhancement request for community-stable images.
- `openssh-clients` package for Amazon Linux
- `openssh` package for ArchLinux
- `openssh` package for BlackArch
- `openssh-client` package for ClearLinux
- `openssh-client` package for KaliLinux
- `openssh-clients` package for Oracle Linux
- `openssh-client` package for ParrotSec
- `openssh-clients` package for Photon
2. Remove the need of `wget` package and use `curl` to download PowerShell package instead.
3. Other minor fixes
- If the PR …
> Add OpenSSH client package to linux community-stable images

- release/preview/alpine311/docker/Dockerfile
- release/preview/alpine311/meta.json
- release/preview/alpine39/docker/Dockerfile
- release/preview/centos7/docker/Dockerfile
- release/preview/centos8/docker/Dockerfile
- release/preview/debian10/docker/Dockerfile
- release/preview/debian11/docker/Dockerfile
- release/preview/debian9/docker/Dockerfile
- release/preview/fedora/docker/Dockerfile
- release/preview/ubuntu16.04/docker/Dockerfile
- release/preview/ubuntu18.04/docker/Dockerfile
- release/preview/ubuntu20.04/docker/Dockerfile
1. Addresses #374 enhancement request for linux preview images.
- `openssh-client` package for Alpine
- `openssh-clients` package for Centos
- `openssh-client` package for Debian
- `openssh-clients` package for Fedora
- `openssh-client` package for Ubuntu
2. Excluded Ubuntu on Arm32v7 platform because I can't get it to work. It threw 0x80004005 error when running in interactive mode with `docker run --rm -ti` command.
- If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title …
> Add OpenSSH client package to linux preview images except Arm32v7

- release/stable/alpine38/docker/Dockerfile
- release/stable/alpine39/docker/Dockerfile
- release/stable/centos7/docker/Dockerfile
- release/stable/centos8/docker/Dockerfile
- release/stable/debian10/docker/Dockerfile
- release/stable/debian11/docker/Dockerfile
- release/stable/debian9/docker/Dockerfile
- release/stable/fedora/docker/Dockerfile
- release/stable/ubuntu16.04/docker/Dockerfile
- release/stable/ubuntu18.04/docker/Dockerfile
1. Addresses #374 enhancement request for linux stable images.
- `openssh-client` package for Alpine
- `openssh-clients` package for Centos
- `openssh-client` package for Debian
- `openssh-clients` package for Fedora
- `openssh-client` package for Ubuntu
2. Excluded Ubuntu on Arm32v7 platform because I can't get it to work. It threw 0x80004005 error when running in interactive mode with docker run --rm -ti command.
- If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title …
> Add OpenSSH client package to linux stable images except Arm32v7

- release/servicing/centos7/docker/Dockerfile
- release/servicing/debian9/docker/Dockerfile
- release/servicing/opensuse423/docker/Dockerfile
- release/servicing/ubuntu16.04/docker/Dockerfile
- release/servicing/ubuntu18.04/docker/Dockerfile
1. Addresses #374 enhancement request for linux servicing images.
- `openssh-clients` package for Centos
- `openssh-client` package for Debian
- `openssh-clients` package for openSUSE
- `openssh-client` package for Ubuntu
- **OR**
> Add OpenSSH client package to linux servicing images

- release/lts/alpine39/docker/Dockerfile
- release/lts/centos7/docker/Dockerfile
- release/lts/centos8/docker/Dockerfile
- release/lts/debian10/docker/Dockerfile
- release/lts/debian11/docker/Dockerfile
- release/lts/debian9/docker/Dockerfile
- release/lts/fedora/docker/Dockerfile
- release/lts/ubuntu16.04/docker/Dockerfile
- release/lts/ubuntu18.04/docker/Dockerfile
1. Addresses #374 enhancement request for linux lts images.
- `openssh-client` package for Alpine
- `openssh-clients` package for Centos
- `openssh-client` package for Debian
- `openssh-clients` package for Fedora
- `openssh-client` package for Ubuntu
2. Excluded Ubuntu on Arm32v7 platform because I can't get it to work. It threw 0x80004005 error when running in interactive mode with docker run --rm -ti command.
- If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and …
> Add OpenSSH client package to linux lts images except Arm32v7

- createManifest.ps1
Fix typo in variable initialization
- **OR**
> Fix typo in variable initialization

- release/community-stable/amazonlinux/test-deps/docker/Dockerfile
- release/community-stable/kalilinux/docker/Dockerfile
- release/preview/alpine310/docker/Dockerfile
- release/preview/alpine310/test-deps/docker/Dockerfile
- release/preview/alpine311/test-deps/docker/Dockerfile
remove usage of `fromtag`
These images use the new system where `fromtag` is not used
- **OR**
> remove usage of `fromtag`

- release/lts/nanoserver1809/docker/Dockerfile
- release/lts/nanoserver1903/docker/Dockerfile
- release/lts/nanoserver1909/docker/Dockerfile
- release/lts/nanoserver2004/docker/Dockerfile
- release/lts/windowsservercore1809/docker/Dockerfile
- release/lts/windowsservercore1903/docker/Dockerfile
- release/lts/windowsservercore1909/docker/Dockerfile
- release/lts/windowsservercore2004/docker/Dockerfile
- release/preview/nanoserver1809/docker/Dockerfile
- release/preview/nanoserver1903/docker/Dockerfile
- release/preview/nanoserver1909/docker/Dockerfile
- release/preview/nanoserver2004/docker/Dockerfile
- release/preview/windowsservercore1809/docker/Dockerfile
- release/preview/windowsservercore1903/docker/Dockerfile
- release/preview/windowsservercore1909/docker/Dockerfile
- release/preview/windowsservercore2004/docker/Dockerfile
- release/servicing/nanoserver1809/docker/Dockerfile
- release/servicing/windowsservercore/docker/Dockerfile
- release/stable/nanoserver1809/docker/Dockerfile
- release/stable/nanoserver1903/docker/Dockerfile
- release/stable/nanoserver1909/docker/Dockerfile
- release/stable/nanoserver2004/docker/Dockerfile
- release/stable/windowsservercore1809/docker/Dockerfile
- release/stable/windowsservercore1903/docker/Dockerfile
- release/stable/windowsservercore1909/docker/Dockerfile
- release/stable/windowsservercore2004/docker/Dockerfile
fix #410 
- Remove `LOCALAPPDATA="C:\Users\ContainerAdministrator\AppData\Local"`
- Update `PSModuleAnalysisCachePath="$LOCALAPPDATA\Microsoft\Windows\PowerShell\docker\ModuleAnalysisCache"` to `PSModuleAnalysisCachePath="C:\Users\Public\AppData\Local\Microsoft\Windows\PowerShell\docker\ModuleAnalysisCache"` instead
- **OR**
> Fix PSModuleAnalysisCachePath path for Windows images

- release/preview/nanoserver1809/docker/Dockerfile
- release/preview/nanoserver1903/docker/Dockerfile
- release/preview/nanoserver1909/docker/Dockerfile
- release/preview/nanoserver2004/dependabot/Dockerfile
- release/preview/nanoserver2004/docker/Dockerfile
- release/preview/windowsservercore2004/dependabot/Dockerfile
- release/stable/nanoserver1809/docker/Dockerfile
- release/stable/nanoserver1903/docker/Dockerfile
- release/stable/nanoserver1909/docker/Dockerfile
- release/stable/nanoserver2004/docker/Dockerfile
- release/stable/windowsservercore1809/docker/Dockerfile
- release/stable/windowsservercore1903/docker/Dockerfile
- release/stable/windowsservercore1909/docker/Dockerfile
- release/stable/windowsservercore2004/docker/Dockerfile
Merge changes from preview into stable for windows images, specifically nanoserver and windowscoreserver. Modified Dockerfiles and meta.json files for these images and removed their dependabot folders.
- **OR**
> merge preview into stable for 7.1 release for windows images

- release/preview/arm32v7/docker/Dockerfile
- release/preview/debian10/docker/Dockerfile
- release/preview/debian11/docker/Dockerfile
- release/preview/ubuntu20.04/docker/Dockerfile
removed outdated linux dependencies from preview images' dockerfiles. Outdated linux dependencies include: liblttng-ust0, libcurl3, libunwind8, libuuid1. 
This PR goes along with the PR in PowerShell [here](https://github.com/PowerShell/PowerShell/pull/14688)
- **OR**
> remove references to outdated dependencies from preview dockerfiles

- build.ps1
- createAllManifests.ps1
- tools/buildHelper/buildHelper.psm1
fix version mismatch is release build
- **OR**
> fix version mismatch in build

- tools/buildHelper/buildHelper.psm1
For images that we know are broken but still wish to make available (just not publish) we include a `isBroken` tag in their meta.json file. In the buildHelper script we check for this tag from the metadata and if found to be true we throw away the image during the build.
- fix typo in buildHelper to check isBroken tag.
- **OR**
> update buildHelper to check if isBroken tag present

- .github/dependabot.yml
- release/lts/nanoserver20H2/dependabot/Dockerfile
- release/lts/nanoserver20H2/docker/Dockerfile
- release/lts/nanoserver20H2/meta.json
- release/lts/windowsservercore20H2/dependabot/Dockerfile
- release/lts/windowsservercore20H2/docker/Dockerfile
- release/lts/windowsservercore20H2/meta.json
- release/preview/nanoserver20H2/docker/Dockerfile
- release/preview/nanoserver20H2/meta.json
- release/preview/windowsservercore20H2/docker/Dockerfile
- release/preview/windowsservercore20H2/meta.json
- release/servicing/nanoserver1809/getLatestTag.ps1
- release/servicing/windowsservercore/getLatestTag.ps1
- release/stable/nanoserver20H2/docker/Dockerfile
- release/stable/nanoserver20H2/meta.json
- release/stable/windowsservercore20H2/docker/Dockerfile
- release/stable/windowsservercore20H2/meta.json
Add images based on Windows 20H2 images.
- **OR**
> Add Windows 20H2 images

- release/lts/nanoserver2022/docker/Dockerfile
- release/lts/nanoserver2022/meta.json
- release/lts/windowsservercore2022/docker/Dockerfile
- release/lts/windowsservercore2022/meta.json
- release/preview/nanoserver2022/docker/Dockerfile
- release/preview/nanoserver2022/meta.json
- release/preview/windowsservercore2022/docker/Dockerfile
- release/preview/windowsservercore2022/meta.json
- release/stable/nanoserver2022/docker/Dockerfile
- release/stable/nanoserver2022/meta.json
- release/stable/windowsservercore2022/docker/Dockerfile
- release/stable/windowsservercore2022/meta.json
Change FROM path to pull base image from different location when Windows LTSC 2022 releases publicly and let `isPrivate` in meta.json be false.
Pull from these locations for windowsservercore and nanoserver, respectively: 
`mcr.microsoft.com/windows/servercore:ltsc2022`
`mcr.microsoft.com/windows/server:ltsc2022`
- **OR**
> Public 2022 images

- .github/dependabot.yml
- release/preview/alpine313/docker/Dockerfile
- release/preview/alpine313/meta.json
- release/preview/alpine313/test-deps/docker/Dockerfile
- release/preview/alpine313/test-deps/meta.json
- release/stable/alpine313/docker/Dockerfile
- release/stable/alpine313/meta.json
- release/stable/alpine313/test-deps/docker/Dockerfile
- release/stable/alpine313/test-deps/meta.json
This PR adds preview and stable docker images based on alpine 3.13.6. The new tag is `3.13`
- **OR**
> Add alpine 3.13.6 images

- release/lts/nanoserver20H2/meta.json
- release/lts/windowsservercore20H2/meta.json
- release/preview/nanoserver20H2/meta.json
- release/preview/windowsservercore20H2/meta.json
- release/stable/nanoserver20H2/meta.json
- release/stable/windowsservercore20H2/meta.json
Remove broken flag from 20H2 images as now supported by ACR. Fixes #552.
- **OR**
> Remove broken flag from 20H2 images as now supported by ACR

- release/preview/alpine312/meta.json
- release/preview/alpine312/test-deps/meta.json
- release/preview/centos7/meta.json
- release/preview/centos7/test-deps/meta.json
- tools/buildHelper/buildHelper.psm1
- vsts-ci.yml
Fix duplicate check failure getting tag list by removing services from duplicate check
* Also fix image sizes
* Also add get-error when dup check fails to know where it failed
* 
> Fix duplicate check failure getting tag list

- release/7-2/ubi84/docker/Dockerfile
- release/7-3/ubi84/docker/Dockerfile
We need Ubi8.4 image to have VERSION_ID of 8.4, not 8.5. `Yum update -y` line of code which updates it to 8.5
> Ubi8.4 image should have Version_ID of 8.4

- release/7-2/ubuntu20.04/meta.json
- release/7-3/ubuntu20.04/meta.json
Ubuntu22.04 will have `latest` and `preview` manifest list tags, so remove those from Ubuntu20.04
> remove manifest list from ubuntu20.04

- release/7-2/ubuntu18.04-arm32v7/docker/Dockerfile
- release/7-2/ubuntu18.04-arm32v7/meta.json
- release/7-2/ubuntu20.04-arm32v7/docker/Dockerfile
- release/7-2/ubuntu20.04-arm32v7/meta.json
- release/7-2/ubuntu20.04/docker/Dockerfile
- release/7-2/ubuntu22.04-arm32v7/docker/Dockerfile
- release/7-2/ubuntu22.04-arm32v7/meta.json
- release/7-3/ubuntu20.04-arm32v7/docker/Dockerfile
- release/7-3/ubuntu20.04-arm32v7/meta.json
- release/7-3/ubuntu22.04-arm32v7/docker/Dockerfile
- release/7-3/ubuntu22.04-arm32v7/meta.json
Images will be given a new tag syntax. For images like Arm32v7, which has a different processor architecture than default amd64, have image name include arm32 (i.e format: os-osversion-arm32).
Adds ubuntu20.04 arm32v7 and ubuntu18.04 arm32v7 images.
> add arm32 ubuntu20 images and fix tag syntax for arm32 ubuntu18

- release/unstable/archlinux/docker/Dockerfile
- release/unstable/blackarch/docker/Dockerfile
Remove use of chmod 777 from unstable images.
> Remove use of `chmod 777`

- .github/workflows/createReminder.yml
- .github/workflows/processReminders.yml
- .github/workflows/rebase.yml
- .github/workflows/update.yml
> Use pwshBot account to allow PR creation in GitHub Workflow

- .vsts-ci/phase.yml
- .vsts-ci/releasePhase.yml
- .vsts-ci/releaseStage.yml
- .vsts-ci/releasebuild.yml
- .vsts-ci/templatesReleasePipeline/releaseStage.yml
> Add arm image support for release

- .vsts-ci/phase.yml
- release/7-4/mariner2/docker/Dockerfile
- unittests/generateMatrixJson.tests.ps1
> Update mariner preview dotnet runtime install

- release/7-4/alpine315/docker/Dockerfile
- release/7-4/alpine315/meta.json
- release/7-4/alpine316/docker/Dockerfile
- release/7-4/alpine316/meta.json
- release/7-4/alpine317/docker/Dockerfile
- release/7-4/alpine317/meta.json
Update the alpine tar gz package name to be linux-musl-x64.tar.gz
> Update the package name for Alpine tar gz packages

- release/7-3/mariner2-arm64/docker/Dockerfile
- release/7-4/mariner2-arm64/docker/Dockerfile
- release/7-4/mariner2/docker/Dockerfile
> Fix TDNF caching issues

- build.ps1
- tools/buildHelper/buildHelper.psm1
- tools/updateYamls/updateBuildYamls.ps1
- tools/updateYamls/updateYamls.md
> Script populate yaml

- .vsts-ci/ltsReleaseStage.yml
- .vsts-ci/previewReleaseStage.yml
- .vsts-ci/stableReleaseStage.yml
update build yamls (<channel>ReleaseStage.yml) for stable 7.4.2, preview 7.5.0-preview.2 and lts 7.2.19
> update build yamls 

- README.md
The MAR link in the readme is broken - no link is shown at all even though it was clearly intended to be one.
> Fix broken MAR link in README

- release/7-2/alpine316/docker/Dockerfile
- release/7-2/alpine316/meta.json
- release/7-2/alpine317/docker/Dockerfile
- release/7-2/alpine317/meta.json
- vsts-ci.yml
Remove Secret Scan stage from PR ci, as it's already enabled
> Remove Secret Scan stage from PR ci, as it's already enabled

- release/7-4/alpine318/docker/Dockerfile
- release/7-4/alpine318/meta.json
- release/7-4/alpine318/test-deps/docker/Dockerfile
- release/7-4/alpine318/test-deps/meta.json
- release/7-4/alpine319/docker/Dockerfile
- release/7-4/alpine319/meta.json
- release/7-4/alpine319/test-deps/docker/Dockerfile
- release/7-4/alpine319/test-deps/meta.json
- release/7-5/alpine318/docker/Dockerfile
- release/7-5/alpine318/meta.json
- release/7-5/alpine318/test-deps/docker/Dockerfile
- release/7-5/alpine318/test-deps/meta.json
- release/7-5/alpine319/docker/Dockerfile
- release/7-5/alpine319/meta.json
- release/7-5/alpine319/test-deps/docker/Dockerfile
- release/7-5/alpine319/test-deps/meta.json
Add alpine 3.18 and 3.19 images for PowerShell 7.4/7.5. They are modified based on alpine 3.17 release
`libssl1.1` is replaced with `libssl3` in alpine 3.19
> Add alpine 3.18 and 3.19 images for PowerShell 7.4/7.5
